/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/hTTPValidationError';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DefaultService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get Api Project
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getApiProjectApiProjectGet(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getApiProjectApiProjectGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getApiProjectApiProjectGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getApiProjectApiProjectGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/api/project`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get File
     * 
     * @param file 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFileFileGet(file: any, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getFileFileGet(file: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getFileFileGet(file: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getFileFileGet(file: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (file === null || file === undefined) {
            throw new Error('Required parameter file was null or undefined when calling getFileFileGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/${encodeURIComponent(String(file))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Project Functions
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProjectFunctionsApiProjectFunctionsGet(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getProjectFunctionsApiProjectFunctionsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getProjectFunctionsApiProjectFunctionsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getProjectFunctionsApiProjectFunctionsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/api/project/functions`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Project Functions Byid
     * 
     * @param functionId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProjectFunctionsByidApiProjectFunctionsByIdFunctionIdGet(functionId: any, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getProjectFunctionsByidApiProjectFunctionsByIdFunctionIdGet(functionId: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getProjectFunctionsByidApiProjectFunctionsByIdFunctionIdGet(functionId: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getProjectFunctionsByidApiProjectFunctionsByIdFunctionIdGet(functionId: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (functionId === null || functionId === undefined) {
            throw new Error('Required parameter functionId was null or undefined when calling getProjectFunctionsByidApiProjectFunctionsByIdFunctionIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/api/project/functions/byId/${encodeURIComponent(String(functionId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Project Functions Roomid
     * 
     * @param roomId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProjectFunctionsRoomidApiProjectFunctionsByRoomIdRoomIdGet(roomId: any, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getProjectFunctionsRoomidApiProjectFunctionsByRoomIdRoomIdGet(roomId: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getProjectFunctionsRoomidApiProjectFunctionsByRoomIdRoomIdGet(roomId: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getProjectFunctionsRoomidApiProjectFunctionsByRoomIdRoomIdGet(roomId: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (roomId === null || roomId === undefined) {
            throw new Error('Required parameter roomId was null or undefined when calling getProjectFunctionsRoomidApiProjectFunctionsByRoomIdRoomIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/api/project/functions/byRoomId/${encodeURIComponent(String(roomId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Project Locations
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProjectLocationsApiProjectLocationsGet(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getProjectLocationsApiProjectLocationsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getProjectLocationsApiProjectLocationsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getProjectLocationsApiProjectLocationsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/api/project/locations`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Project Locations Space Byid
     * 
     * @param spaceId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProjectLocationsSpaceByidApiProjectLocationsSpaceSpaceIdGet(spaceId: any, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getProjectLocationsSpaceByidApiProjectLocationsSpaceSpaceIdGet(spaceId: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getProjectLocationsSpaceByidApiProjectLocationsSpaceSpaceIdGet(spaceId: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getProjectLocationsSpaceByidApiProjectLocationsSpaceSpaceIdGet(spaceId: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (spaceId === null || spaceId === undefined) {
            throw new Error('Required parameter spaceId was null or undefined when calling getProjectLocationsSpaceByidApiProjectLocationsSpaceSpaceIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/api/project/locations/space/${encodeURIComponent(String(spaceId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Root
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRootGet(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getRootGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getRootGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getRootGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
